name: 'Apply on non-main and feature branches'

on:
  push:
    paths:
      - 'development/**'
      - '.github/workflows/dev*.yaml'
      - './**.tf'
    branches:
      - 'main'

env:
  TF_LOG: INFO
  TF_INPUT: false

permissions:
  id-token: write
  contents: read

jobs:
  terraform:
    name: 'Terraform Apply on Push'
    runs-on: ubuntu-latest
    env:
      FIREFLY_ACCESS_KEY: ${{ secrets.FIREFLY_ACCESS_KEY }}
      FIREFLY_SECRET_KEY: ${{ secrets.FIREFLY_SECRET_KEY }}
      STORAGE_ACCOUNT: ${{ secrets.STORAGE_ACCOUNT }}
      CONTAINER_NAME: ${{ secrets.CONTAINER_NAME }}
      RESOURCE_GROUP_NAME: ${{ secrets.RESOURCE_GROUP_NAME }}
      ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}

    # Use the Bash shell
    defaults:
      run:
        shell: bash
        working-directory: './development'

    steps:
    # Checkout the repository to the GitHub Actions runner
    - name: Checkout
      uses: actions/checkout@v3

    # Install the preferred version of Terraform CLI 
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2

    # Log into Azure with OIDC integration
    - name: 'Az CLI login'
      uses: azure/login@v1
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

    # Run Terraform init
    - name: Terraform Init
      id: init
      run: terraform init -backend-config="storage_account_name=$STORAGE_ACCOUNT" -backend-config="container_name=$CONTAINER_NAME" -backend-config="resource_group_name=$RESOURCE_GROUP_NAME"

    # Run Terraform apply
    - name: Terraform Apply
      id: apply
      run: terraform apply -auto-approve -json > apply_log.jsonl

    - name: Firefly Post Apply
      if: steps.apply.outcome == 'success'
      uses: gofireflyio/fireflyci@v0.3.3
      with:
        apply-log-file: ./development/apply_log.jsonl
        command: post-apply
        context: ""
        workspace: dev-azure-taconet
      continue-on-error: true

